"""Backend-agnostic network-emulation interface for Olympus environments.

A *backend* turns an episode's link/traffic spec into real TCP flows that the
congestion-control listener can attach to. Mininet is the reference backend
(``olympus/environments/mininet/env.py``); alternatives live under
``olympus/environments/<type>/env.py`` and are selected by the environment
``type`` in config and instantiated through ``make_env`` (see
``olympus/environments/__init__.py``).

The binding invariant every backend MUST honor — the "cport contract":

    Flow identity == iperf3 client source port.

    Each flow ``i`` is generated by an iperf3 client bound to source port
    ``cport`` (or ``cport + i - 1`` when ``unique_cports`` is set). The
    listener (``oc_listener`` / ``astraea_listener``) is started with
    ``--cport`` and matches kernel sockets on that source port to read and
    write cwnd. A backend therefore must:

      * launch real TCP flows whose client-side source port is exactly the
        requested cport (honoring ``unique_cports``);
      * run them where the listener's socket scan can observe them;
      * keep parallel-slot isolation so concurrent instances never collide on
        source ports or emulator resources (see ``instance_id``);
      * write the per-flow iperf artifacts the downstream parsers read
        (``/tmp/iperf_{cport}_{i}.json`` and the matching server file).

Universal constructor kwargs (a backend may accept extras, but these carry the
shared meaning the orchestrator relies on):

    n               number of sender/receiver flow pairs
    bw              bottleneck bandwidth (Mbps)
    delay           one-way propagation delay (ms)
    qsize           bottleneck queue size (overrides bdp_mult when set)
    bdp_mult        queue size as a multiple of BDP
    loss            bottleneck loss percentage (optional)
    duration        per-episode iperf runtime (s)
    cport           iperf3 client source port — the flow-identity key above
    cc_algo         TCP congestion-control name passed to iperf3 (-C)
    instance_id     isolation-slot id for parallel runs (None = legacy/no prefix)
    unique_cports   give flow i source port cport+i-1 instead of a shared cport
    per_flow_delays optional list of per-flow one-way delays (ms)
"""

from abc import ABC, abstractmethod


class NetworkEnv(ABC):
    """Lifecycle a network backend must implement for the orchestrator.

    The orchestrator drives exactly this surface: ``start`` once, optional live
    ``set_link`` changes from a scheduler thread, one ``run_iperf`` to launch
    the flows, then ``stop`` at teardown. Implementations honor the cport
    contract documented in this module's docstring.
    """

    @abstractmethod
    def start(self) -> None:
        """Bring up the topology / namespaces and apply the initial link."""

    @abstractmethod
    def set_link(self, bw=None, delay=None, loss=None) -> None:
        """Live-update bottleneck bandwidth, delay, and/or loss mid-episode.

        Must be safe to call from a background scheduler thread. A backend that
        cannot retune in place should at minimum accept the call without error.
        """

    @abstractmethod
    def run_iperf(self, monitor_interval=0.1, start_delays=None,
                  flow_durations=None) -> None:
        """Launch the iperf3 servers and clients that realize every flow.

        ``start_delays`` optionally staggers flow start times (s, one per flow);
        ``flow_durations`` optionally sets an exact runtime per flow.
        """

    @abstractmethod
    def stop(self) -> None:
        """Tear down the topology / namespaces and release all resources."""
